# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ccgdocker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://azacrn.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d2b5b80f71ca42179457b90bbcca3175 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_67ea715f015a4ca8a5533469ef9b2c2c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: azacrn.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d2b5b80f71ca42179457b90bbcca3175 }}/ccgpmbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ccgdocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_52cbcf04ff934d42ad2bb89118f7aac7 }}
        images: 'azacrn.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d2b5b80f71ca42179457b90bbcca3175 }}/ccgpmbot:${{ github.sha }}'